[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "scrna"
version = "0.1.0"
description = "Single-cell RNA analysis functions"
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}
authors = [
    {name = "Your Name", email = "your.email@example.com"},
]
keywords = ["single-cell", "rna-seq", "bioinformatics", "analysis"]
classifiers = [
    "Intended Audience :: Science/Research",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
]
dependencies = [
    "numpy",
    "scipy",
    "matplotlib",
    "pandas",
    "seaborn",
    "anndata",
    "scanpy",
    "cellphonedb",
    "celltypist",
    "decoupler",
    "pydeseq2",
    "fpdf2",
    "pdf2image",
    "dataframe-image",
    "harmonypy",
]

[project.optional-dependencies]
gpu = ["rapids-singlecell"]
dev = [
    "pytest",
    "black",
    "flake8",
    "mypy",
]

[project.urls]
Homepage = "https://github.com/drgmk/scrna"
Repository = "https://github.com/drgmk/scrna"
Issues = "https://github.com/drgmk/scrna/issues"

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["scrna"]

[project.scripts]
scrna_firstlook = "scrna.scripts.firstlook:main"

[tool.black]
line-length = 88
target-version = ['py38']

[tool.mypy]
python_version = "3.8"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
